import SwiftUI

// PULSE native setup stub (clean-room, PULSE-native code — no third-party lineage).
// Thin installer in the Hermes-Setup shape: a tiny signed app that downloads
// scripts/install.sh from OUR repo and runs its stage protocol
// (--manifest / --stage NAME --json), showing live progress. All heavy work
// (uv, Python, Node, tools, checkout) happens on the user's machine via the
// pm runtime — nothing is bundled.
//
// Build-time config lives in SetupConfig.swift (generated by
// scripts/build-setup-dmg.sh): repo URL, branch, optional commit pin.
// Test hooks (documented, not secret): env PULSE_HOME respected as-is;
// PULSE_SETUP_EXTRA_ARGS appended to every stage call (e.g. "--skip-browser"
// to slim a test install); --auto-test CLI arg starts installing on appear.

struct SetupConfig {
    static let repoURL = "__PULSE_REPO_URL__"
    static let branch = "__PULSE_BRANCH__"
    static let pinCommit = "__PULSE_PIN_COMMIT__"
    static let appName = "PULSE"
}

struct Stage: Identifiable, Hashable {
    let id: String
    let title: String
    let needsInput: Bool
}

enum RunState: Equatable {
    case idle
    case running
    case done
    case failed(String)
}

@MainActor
final class InstallerModel: ObservableObject {
    @Published var stages: [Stage] = []
    @Published var currentIndex: Int = -1
    @Published var log: String = ""
    @Published var state: RunState = .idle
    @Published var skippedNote: String = ""

    private var scriptPath: String = ""
    private let autoTest = CommandLine.arguments.contains("--auto-test")
    private var extraArgs: [String] {
        (ProcessInfo.processInfo.environment["PULSE_SETUP_EXTRA_ARGS"] ?? "")
            .split(separator: " ").map(String.init).filter { !$0.isEmpty }
    }

    func appendLog(_ line: String) {
        log += line + "\n"
        if log.count > 60000 { log = String(log.suffix(60000)) }
    }

    func start() {
        guard state == .idle else { return }
        state = .running
        appendLog("☤ \(SetupConfig.appName) Setup — \(SetupConfig.repoURL)")
        Task.detached { [weak self] in
            await self?.runAll()
        }
    }

    private func shell(_ args: [String], env: [String: String]? = nil) -> (Int32, String) {
        let p = Process()
        p.executableURL = URL(fileURLWithPath: "/bin/bash")
        p.arguments = args
        if let env = env {
            var e = ProcessInfo.processInfo.environment
            for (k, v) in env { e[k] = v }
            p.environment = e
        }
        let pipe = Pipe()
        p.standardOutput = pipe
        p.standardError = pipe
        do { try p.run() } catch { return (1, "cannot launch bash: \(error)") }
        let data = pipe.fileHandleForReading.readDataToEndOfFile()
        p.waitUntilExit()
        return (p.terminationStatus, String(data: data, encoding: .utf8) ?? "")
    }

    private func runAll() async {
        // 1. Fetch the installer from OUR repo (pinned branch/commit).
        let tmp = FileManager.default.temporaryDirectory
            .appendingPathComponent("pulse-setup-\(Int(Date().timeIntervalSince1970))")
        do { try FileManager.default.createDirectory(at: tmp, withIntermediateDirectories: true) }
        catch { await self.fail("cannot create temp dir"); return }
        let script = tmp.appendingPathComponent("install.sh").path
        let rawURL: String
        if let comps = URLComponents(string: SetupConfig.repoURL),
           comps.host == "github.com" {
            let path = comps.path.trimmingCharacters(in: CharacterSet(charactersIn: "/"))
                .replacingOccurrences(of: ".git", with: "")
            let ref = SetupConfig.pinCommit.isEmpty ? SetupConfig.branch : SetupConfig.pinCommit
            // Raw file serving only resolves branches/tags, not SHAs — pin via branch.
            rawURL = "https://raw.githubusercontent.com/\(path)/\(SetupConfig.branch)/scripts/install.sh"
            _ = ref
        } else {
            await self.fail("bad repo URL in build config"); return
        }
        await self.note("Downloading installer from \(SetupConfig.repoURL) …")
        let (dlCode, dlOut) = shell(["-c", "curl -fsSL \(rawURL) -o \(script) && chmod +x \(script) && echo OK"])
        guard dlCode == 0, dlOut.contains("OK") else {
            await self.fail("installer download failed. Check your network and retry.\n\(dlOut)"); return
        }
        await self.setScript(script)

        // 2. Read the stage manifest (the protocol install.sh speaks).
        let (mCode, mOut) = shell([script, "--manifest"])
        guard mCode == 0,
              let mData = mOut.data(using: .utf8),
              let manifest = try? JSONSerialization.jsonObject(with: mData) as? [String: Any],
              let rawStages = manifest["stages"] as? [[String: Any]] else {
            await self.fail("installer manifest unreadable:\n\(mOut)"); return
        }
        let parsed: [Stage] = rawStages.compactMap { s in
            guard let n = s["name"] as? String, let t = s["title"] as? String else { return nil }
            return Stage(id: n, title: t, needsInput: (s["needs_user_input"] as? Bool) ?? false)
        }
        guard !parsed.isEmpty else { await self.fail("empty stage list"); return }
        await self.setStages(parsed)

        // 3. Run every stage; interactive ones are skipped (same as --non-interactive).
        var skipped: [String] = []
        for (i, stage) in parsed.enumerated() {
            await self.setCurrent(i)
            if stage.needsInput {
                skipped.append(stage.title)
                await self.note("Skipping '\(stage.title)' (needs you) — run `pulse setup` after.")
                continue
            }
            var args = [script, "--stage", stage.id, "--json",
                        "--non-interactive", "--branch", SetupConfig.branch] + extraArgs
            if !SetupConfig.pinCommit.isEmpty { args += ["--commit", SetupConfig.pinCommit] }
            let (code, out) = shell(args)
            await self.note(out.trimmingCharacters(in: .whitespacesAndNewlines))
            let frameOk: Bool = out.split(separator: "\n").compactMap { line -> Bool? in
                guard let d = line.data(using: .utf8),
                      let j = try? JSONSerialization.jsonObject(with: d) as? [String: Any] else { return nil }
                return j["ok"] as? Bool
            }.last ?? (code == 0)
            if !frameOk {
                await self.fail("Stage '\(stage.title)' failed.\n\(out.suffix(2000))")
                return
            }
        }
        await self.finish(skipped: skipped)
    }

    // MARK: - main-actor hops
    private func setScript(_ p: String) { scriptPath = p }
    private func setStages(_ s: [Stage]) { stages = s }
    private func setCurrent(_ i: Int) { currentIndex = i }
    private func note(_ t: String) { appendLog(t) }
    private func fail(_ t: String) { state = .failed(t); appendLog("✗ \(t)") }
    private func finish(skipped: [String]) {
        currentIndex = stages.count
        skippedNote = skipped.isEmpty ? "" : "Skipped (do these in a terminal): " + skipped.joined(separator: ", ")
        state = .done
        appendLog("✓ \(SetupConfig.appName) install complete. Run `pulse setup`, then `pulse`.")
    }

    func beginIfAutoTest() {
        if autoTest { start() }
    }
}

struct SetupView: View {
    @StateObject private var model = InstallerModel()

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            HStack(spacing: 12) {
                Circle()
                    .fill(LinearGradient(colors: [.orange, .blue], startPoint: .topLeading, endPoint: .bottomTrailing))
                    .frame(width: 44, height: 44)
                    .overlay(Circle().stroke(Color.white.opacity(0.25), lineWidth: 1))
                VStack(alignment: .leading, spacing: 2) {
                    Text("Install \(SetupConfig.appName)")
                        .font(.title2).fontWeight(.light)
                    Text(SetupConfig.repoURL.replacingOccurrences(of: "https://github.com/", with: ""))
                        .font(.caption).foregroundStyle(.secondary)
                        .textSelection(.enabled)
                }
                Spacer()
            }
            if !model.stages.isEmpty {
                ProgressView(value: Double(max(model.currentIndex, 0)),
                             total: Double(model.stages.count))
                    .tint(.orange)
                Text(statusLine).font(.callout).foregroundStyle(.secondary)
                List(model.stages) { st in
                    let idx = model.stages.firstIndex(of: st) ?? -1
                    HStack {
                        Text(idx < model.currentIndex || model.state == .done ? "✓" :
                                (idx == model.currentIndex ? "●" : "○"))
                            .foregroundStyle(idx == model.currentIndex ? .orange : .secondary)
                            .frame(width: 20)
                        Text(st.title)
                        Spacer()
                        if st.needsInput { Text("you").font(.caption).foregroundStyle(.secondary) }
                    }
                }
                .frame(minHeight: 180)
            } else {
                Text("Fetching the install plan…").foregroundStyle(.secondary)
                ProgressView().tint(.orange)
            }
            TextEditor(text: .constant(model.log))
                .font(.system(size: 11, design: .monospaced))
                .frame(minHeight: 120)
                .border(Color.secondary.opacity(0.3))
                .allowsHitTesting(false)
            if case .failed(let msg) = model.state {
                Text(msg).font(.callout).foregroundStyle(.red)
                    .lineLimit(4).textSelection(.enabled)
            }
            if !model.skippedNote.isEmpty && model.state == .done {
                Text(model.skippedNote).font(.callout).foregroundStyle(.secondary)
            }
            HStack {
                Spacer()
                if model.state == .idle {
                    Button("Install") { model.start() }.buttonStyle(.borderedProminent).tint(.orange)
                } else if model.state == .done {
                    Button("Open Terminal") { openTerminal() }
                    Button("Quit") { NSApplication.shared.terminate(nil) }.buttonStyle(.borderedProminent).tint(.orange)
                } else if case .failed = model.state {
                    Button("Retry") { retry() }
                    Button("Quit") { NSApplication.shared.terminate(nil) }
                } else {
                    ProgressView().tint(.orange)
                    Text("Installing…").foregroundStyle(.secondary)
                }
            }
        }
        .padding(20)
        .frame(minWidth: 600, minHeight: 560)
        .preferredColorScheme(.dark)
        .onAppear { model.beginIfAutoTest() }
    }

    private var statusLine: String {
        if model.state == .done { return "Complete" }
        if model.currentIndex >= 0 && model.currentIndex < model.stages.count {
            return model.stages[model.currentIndex].title
        }
        return "Working…"
    }

    private func openTerminal() {
        let p = Process()
        p.executableURL = URL(fileURLWithPath: "/usr/bin/open")
        p.arguments = ["-a", "Terminal"]
        try? p.run()
    }

    private func retry() {
        // Simplest correct retry: relaunch a fresh copy of ourselves.
        let url = Bundle.main.bundleURL
        let p = Process()
        p.executableURL = URL(fileURLWithPath: "/usr/bin/open")
        p.arguments = ["-n", url.path]
        try? p.run()
        NSApplication.shared.terminate(nil)
    }
}

@main
struct PulseSetupApp: App {
    var body: some Scene {
        WindowGroup("Install PULSE") { SetupView() }
            .windowResizability(.contentSize)
    }
}
